logging:
  level:
    com.dng.api: INFO
    org.springframework.boot.context: INFO
    org.springframework.security: DEBUG
    org:
      springframework:
        boot:
          autoconfigure:
            security: DEBUG

server:
  compression:
    enabled: true
  port: 8080
  servlet:
    context-path: /training
springfox:
  documentation:
    swagger.v2.path: /v2/api-docs
    info:
      title:
      description: DNG Training API Docs.
      version: 1.0
    base-package: com.dng.api

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'
security:
    oauth2:
      client:
        clientId: 680829588145-ei2colnlpfvmlkcdjmbsla3vja03fkaj.apps.googleusercontent.com
        clientSecret: T9MjO2RfGMe3I3TgIocY8XmM
        accessTokenUri: https://www.googleapis.com/oauth2/v4/token
        userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
        clientAuthenticationScheme: header
        authenticationScheme: header
        scope: profile
      resource:
          userInfoUri: https://www.googleapis.com/userinfo/v2/me

spring:
  application:
    name: training
  logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
    enabled: true
    url: elk:5045
  devtools:
    restart:
      enabled: true
  messages:
    basename: i18n/messages
  cache:
    type: redis
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: training

  datasource:
    platform: postgresql
    url: jdbc:postgresql://postgres:5432/training
    username: postgres
    password: admin
    continue-on-error: true

  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
