version: "3.7"
services:
  app:
    image: @project.artifactId@:@project.version@
    ports: 
      - 8080:8080
      - 9090:9090
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.20'
          memory: 128M
      mode: replicated
      replicas: 1
    depends_on:
      
      - postgres
      - redis
      - mongodb
    networks:
      - backend
      - frontend
    links:
      
      - postgres:postgres
      - redis:redis
      - mongodb:mongodb
  
  postgres:
    image: postgres:11.2-alpine
    ports: 
      - 5432:5432
    networks:
      - backend
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=pgdbtraining@123"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.20'
          memory: 128M
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  redis:
    image: redis:5.0.4-alpine
    ports: 
      - 6379:6379
    networks:
      - backend
    volumes:
      - redisdata:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.20'
          memory: 128M
      mode: replicated
      replicas: 1
  mongodb:
    image: bitnami/mongodb:4.1
    ports: 
      - 27017:27017
    networks:
      - backend
    volumes:
      - mongodbdata:/bitnami
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.20'
          memory: 128M
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  
networks:
  backend:
  frontend:
volumes:
    
    influxdbdata:
    redisdata:
    mongodbdata:
    